language: node_js
node_js:
  - '0.10'
  - '0.8'
after_success:
    "test": istanbul cover _mocha --report lcovonly -- test/*.js --reporter list --timeout 100000 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage